### ISSUE TITLE
Move Api into infra

### ISSUE THREAD

**Issue by moeriki** [OpenSkool/OpenSkool#186]
We currently have a provisional dev setup where each resource is manually created and managed. This has worked well but we should automate this so we can have multiple environments and multiple skools without having to do manual resource management.

## Prerequisites

- #188 

## Acceptance Criteria

- The current Api service is part of the infrastructure setup
  - CI is updated to deploy into k8s
  - We'll work hard to have a Docker image as small as possible

## ToDo

- [x] Figure out how to seed
- [x] Verify health endpoint
- [x] Setup deploy pipeline
- [x] Migrate Api Db at container start-up with containerInit
